apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: devops-test
spec:
  ports:
    - port: 3000
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: localhost:5000/api:latest
        env:
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: mydb
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: CONFIG_PATH
          value: /config/config.yaml
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: api-config-volume
          mountPath: /config
      volumes:
      - name: api-config-volume
        configMap:
          name: api-config
